// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWTuYddYBX53m0_J6OEtBb7eMjUq7vHjc',
    appId: '1:485728455682:web:c474a1bb301a6fffd5eb1b',
    messagingSenderId: '485728455682',
    projectId: 'tripjoy-d309f',
    authDomain: 'tripjoy-d309f.firebaseapp.com',
    storageBucket: 'tripjoy-d309f.appspot.com',
    measurementId: 'G-NGMW6T2S41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfuBkl09OlnQStII4Bxl_IYScQoRtm7oA',
    appId: '1:485728455682:android:3136360daec56f6dd5eb1b',
    messagingSenderId: '485728455682',
    projectId: 'tripjoy-d309f',
    storageBucket: 'tripjoy-d309f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwqYAoqX2i5xDi9cIHvZXRTveYairf0Uk',
    appId: '1:485728455682:ios:8627a554d116d3fad5eb1b',
    messagingSenderId: '485728455682',
    projectId: 'tripjoy-d309f',
    storageBucket: 'tripjoy-d309f.appspot.com',
    iosBundleId: 'com.leapcompany.tripjoy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwqYAoqX2i5xDi9cIHvZXRTveYairf0Uk',
    appId: '1:485728455682:ios:8627a554d116d3fad5eb1b',
    messagingSenderId: '485728455682',
    projectId: 'tripjoy-d309f',
    storageBucket: 'tripjoy-d309f.appspot.com',
    iosBundleId: 'com.leapcompany.tripjoy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWTuYddYBX53m0_J6OEtBb7eMjUq7vHjc',
    appId: '1:485728455682:web:3947f98375721c23d5eb1b',
    messagingSenderId: '485728455682',
    projectId: 'tripjoy-d309f',
    authDomain: 'tripjoy-d309f.firebaseapp.com',
    storageBucket: 'tripjoy-d309f.appspot.com',
    measurementId: 'G-LGEXYD6845',
  );

}